### ISSUE TITLE
non file-like formatters causes ImportError

### ISSUE THREAD

**Issue by ajmirsky** [nipo/hrdc#6]
Writing a non-file-like formatter with `MainMerge` and `RangeMerge` are causing exceptions:

```
Exception ignored in: <function MainMerge.__del__ at 0x1033b9d00>
Traceback (most recent call last):
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/main_merge.py", line 80, in __del__
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/physical_merge.py", line 22, in append
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function RangeMerge.__del__ at 0x1033ba2a0>
Traceback (most recent call last):
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/range_merge.py", line 41, in __del__
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/range_merge.py", line 17, in flush
```

Here is the snippet:

```
from hrdc.usage import *
from hrdc.descriptor import *
from hrdc.stream import formatter
from hrdc.stream import optimizer


mouse = Collection(Collection.Application, desktop.Mouse,
                   Value(Value.Input, desktop.X, 8,
                         flags = Value.Variable | Value.Relative,
                         logicalMin = -127, logicalMax = 127),
                   Value(Value.Input, desktop.Y, 8,
                         flags = Value.Variable | Value.Relative,
                         logicalMin = -127, logicalMax = 127),
                   Value(Value.Input, button.Button(1), 1,
                         logicalMin = 0, logicalMax = 1),
                   Value(Value.Input, button.Button(2), 1,
                         logicalMin = 0, logicalMax = 1),
                   Value(Value.Input, button.Button(3), 1,
                         logicalMin = 0, logicalMax = 1),
                   )


class HexList(formatter.Formatter):
    def __init__(self, output):
        self.output = output

    def append(self, i):
        blob = " ".join(["%02x" % x for x in i.bytes()])
        self.output.append(blob + "\n")

_list = []
_output = HexList(_list)
_output = optimizer.Optimizer.new(_output)
_visitor = streamer.Streamer(_output)
mouse.accept(_visitor)
```

( If you comment out the `_output = optimizer.Optimizer.new(_output)`, it works fine. )

**Comment by ajmirsky** [comment]
looks like by using `__del__` in `RangeMerge` and `MainMerge`, that function gets called after the last line of the program, so if the file handler is closed (or the output is accessed prior as above) causes an error:

```
from hrdc.stream.formatter.hex import Hex
f = open('output.txt', 'w')
_output = Hex(f)
_output = optimizer.Optimizer.new(_output)
_visitor = streamer.Streamer(_output)
mouse.accept(_visitor)
f.close()
```

causes:

```
Exception ignored in: <function RangeMerge.__del__ at 0x1013c22a0>
Traceback (most recent call last):
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/range_merge.py", line 41, in __del__
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/range_merge.py", line 32, in flush
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/optimizer/usage_page.py", line 25, in append
  File "/Users/amirsky/dev/bonsai/hid_gen/.hid_gen/src/hrdc/hrdc/stream/formatter/hex.py", line 9, in append
ValueError: I/O operation on closed file.
```

**Comment by nipo** [comment]
Indeed, this happens because working on the global scope of __main__ module.
We need to know when stream end happens. For now, we rely on scope and GC to notify us. This is somewhat weak.

Simple workaround: call these from a function as in:

```
def process(desc):
    _list = []
    _output = HexList(_list)
    _output = optimizer.Optimizer.new(_output)
    _visitor = streamer.Streamer(_output)
    desc.accept(_visitor)
    return _list

blob = process(mouse)
print(''.join(blob))
```

Other workaround: explicitly delete output stream and references:

```
_list = []
_output = HexList(_list)
_output = optimizer.Optimizer.new(_output)
_visitor = streamer.Streamer(_output)
mouse.accept(_visitor)
del _visitor
del _output
print(''.join(_list))
```

For this second option, this makes the calling somewhat misleading.
Real fix would be to change streamer from a push API to an iterator. This would involve rewriting most of the library. I'll postpone this to a later rework.

In the mean time, in 3fe2f2e14d, I added a close() method to Stream, needs to be explicitly called when using raw calls like you do.

**Comment by ajmirsky** [comment]
thanks!

calling close on a stream seems like a consistent approach.
